name: Build Backstage TechDocs

on:
  push:
    branches:
      - feat/backstage-techdocs-builder

jobs:
  build: 
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material

      - name: Build Documentation
        run: mkdocs build --config-file ./docs/mkdocs.yml

      - name: Configure AWS Credentials
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=eu-north-1

      - name: Extract component info and Sync to S3
        run: |
          aws s3 sync site/ s3://backstage-compiled-docs/hackathon/component/ibm
